### ISSUE TITLE
Fails to work with PHP 8.4

### ISSUE THREAD

**Issue by chrisl8** [adminerevo/adminerevo#214]
Works fine with PHP 8.3, but fails with PHP 8.4

Obviously not a show stopper, but it would be nice to fix that.

The first error I saw was `Uncaught Error: Undefined constant "SID" in /var/www/html/adminer.php:53` in case that helps, but I presume that that may be the first of many.

I can dig into the errors and causes later if you like, but it might be an easy fix. I wanted to post this though to let you know before you get flooded with notices about this.

**Comment by LionelLaffineur** [comment]
Hi @chrisl8,
I've done the setup of PHP8.4 and made a few clicks in AdminerEvo without getting that error.
Could you tell me what you were doing when you got that error ?  In case it was at login, or just after, can you say a little more about the setup you are using ?
Regards,
L.

**Comment by mckaygerhard** [comment]
The usage of SID is on https://github.com/adminerevo/adminerevo/blob/19ac89adbdde7e8cd5b4519727d298fb53e799e3/adminer/include/functions.inc.php#L343 where those check are preformed..  the code assumes `restart_session` create it from the configuration variable `session.use_trans_sid` trans sid support is disabled by default and is enabled in `[adminer/include/bootstrap.inc.php](https://github.com/adminerevo/adminerevo/blob/19ac89adbdde7e8cd5b4519727d298fb53e799e3/adminer/include/bootstrap.inc.php#L41)` but this behaviour depends on instalations.

This can be a bug @LionelLaffineur so must be valid but..


so @chrisl8  you must do proper install the place you use is not a good one. use "aliasing" and put in other place.. where the adminer can modify their env, the `/var/www...` etc etc is not a right place

**Comment by mckaygerhard** [comment]
also issue title must be changed then also to something like "**undefined vars or globasl indefined vars as errors on php 8.4**"

**Comment by chrisl8** [comment]
I am still digging into this, just short on free time recently.

I'm running this in Docker on Linux.

It fails as soon as it tries to start up:

```
adminer  | [9] [Tue Nov 26 14:53:31 2024] PHP 8.4.1 Development Server (http://[::]:8080) started
adminer  | [10] [Tue Nov 26 14:53:31 2024] PHP 8.4.1 Development Server (http://[::]:8080) started
adminer  | [11] [Tue Nov 26 14:53:31 2024] PHP 8.4.1 Development Server (http://[::]:8080) started
adminer  | [1] [Tue Nov 26 14:53:31 2024] PHP 8.4.1 Development Server (http://[::]:8080) started
adminer  | [12] [Tue Nov 26 14:53:31 2024] PHP 8.4.1 Development Server (http://[::]:8080) started
adminer  | [1] [Tue Nov 26 14:53:36 2024] [::ffff:127.0.0.1]:48748 Accepted
adminer  | [1] [Tue Nov 26 14:53:36 2024] [::ffff:127.0.0.1]:48748 [200]: GET / - Uncaught Error: Undefined constant "SID" in /var/www/html/adminer.php:53
adminer  | Stack trace:
adminer  | #0 /var/www/html/adminer.php(1458): sid()
adminer  | #1 /var/www/html/index.php(49): require('/var/www/html/a...')
adminer  | #2 {main}
adminer  |   thrown in /var/www/html/adminer.php on line 53
adminer  | [1] [Tue Nov 26 14:53:36 2024] [::ffff:127.0.0.1]:48748 Closing
adminer  | [9] [Tue Nov 26 14:53:41 2024] Failed to poll event
adminer  | [10] [Tue Nov 26 14:53:41 2024] [::ffff:127.0.0.1]:48752 Accepted
adminer  | [10] [Tue Nov 26 14:53:41 2024] [::ffff:127.0.0.1]:48752 [200]: GET / - Uncaught Error: Undefined constant "SID" in /var/www/html/adminer.php:53
```

It works fine with PHP 8.3

I will dig into it further when I have time. I was hoping it was something easy and obvious, but clearly not.
It could be a problem with my setup that PHP 8.3 covers for that 8.4 does not.

**Comment by chrisl8** [comment]
Hopefully you can reproduce this:

Here is my Dockerfile:

```
FROM php:8.3

RUN apt-get update && apt-get install --no-install-recommends -y libpq-dev

RUN docker-php-ext-install mysqli pdo pdo_mysql pgsql pdo_pgsql && docker-php-ext-enable pdo_mysql pdo_pgsql

RUN curl -fsSL "https://github.com/adminerevo/adminerevo/releases/download/v4.8.4/adminer-4.8.4.php" -o /var/www/html/index.php

ENV PHP_CLI_SERVER_WORKERS=4
CMD [ "php", "-S", "[::]:8080", "-t", "/var/www/html" ]
```
This works fine:
![image](https://github.com/user-attachments/assets/77e42c9e-70e2-4575-91ba-0363c9f479e8)


Changing `FROM php:8.3` to `FROM php:8.4` results in this:
![image](https://github.com/user-attachments/assets/68b24c5a-9dab-41d6-abd9-25c2d3fcd350)

Text:
```

Deprecated: Min_DB::rootQuery(): Implicitly marking parameter $Db as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/index.php on line 1091

Deprecated: Min_DB::query(): Implicitly marking parameter $Db as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/index.php on line 1095

Warning: session_cache_limiter(): Session cache limiter cannot be changed after headers have already been sent in /var/www/html/index.php on line 209

Warning: session_name(): Session name cannot be changed after headers have already been sent in /var/www/html/index.php on line 209

Warning: session_set_cookie_params(): Session cookie parameters cannot be changed after headers have already been sent in /var/www/html/index.php on line 209

Warning: session_start(): Session cannot be started after headers have already been sent in /var/www/html/index.php on line 209

Warning: Undefined global variable $_SESSION in /var/www/html/index.php on line 213

Warning: Undefined global variable $_SESSION in /var/www/html/index.php on line 215

Warning: Undefined global variable $_SESSION in /var/www/html/index.php on line 215

Fatal error: Uncaught Error: Undefined constant "SID" in /var/www/html/index.php:53 Stack trace: #0 /var/www/html/index.php(1458): sid() #1 {main} thrown in /var/www/html/index.php on line 53
```

**Comment by alxndr-w** [comment]
> Deprecated: Min_DB::query(): Implicitly marking parameter $Db as nullable is deprecated, the explicit nullable type must be used instead in [src\addons\adminer\vendor\adminer.php](vscode://file/C:\laragon\www\project\src\addons\adminer\vendor\adminer.php:1095) on line 1095

I want to add this one.
